### ISSUE TITLE
Intro section

### ISSUE THREAD

**Issue by ansost** [tacosConference/tacosConference.github.io#10]
Replace the section that currently has the facebook video with a section about what the tacos is etc. 
A basic description for people who dont know what it is.

**Comment by stonehenge0** [comment]
Proposal for a "What is the TaCos" section. Feel free to add/change things

What is the TaCos?

The TaCos is a conference for Computational Linguistics and neighboring disciplines. It takes place once a year and is organized by students of a different university every year.
Students from Germany, the Benelux countries and other European countries come together to present and discuss their research and ideas around everything Computational Linguistics.

For information on previous TaCos conferences, look here:
https://71.stuts.de/ (joined website from last year's STUTS (student conference for Linguistics) and TaCos)
