### ISSUE TITLE
Extend CfP

### ISSUE THREAD

**Issue by BraveMoneyLute** [tacosConference/tacosConference.github.io#125]
20th May new deadline, ask everyone to hand in papers

**Comment by ansost** [comment]
when should this be done?

**Comment by BraveMoneyLute** [comment]
I dont know I came out of class 30 mins ago wait let me see if I can do something

**Comment by BraveMoneyLute** [comment]
ToDo: Change this on the actual CfP page, too, I only edited this on the front page so far
