### ISSUE TITLE
Add previous Tacos/Stus pages reference

### ISSUE THREAD

**Issue by ansost** [tacosConference/tacosConference.github.io#15]
Below speakers, there is abutton that is supposed to link to previous conference website. That link needs to be fixed. Particularly useful because we dont have that much content yet, so people can look at what the previous ones loked like.

Either one or more prvious ones.

**Comment by ansost** [comment]
#### The relevant files are in `/_includes/2023_data/`

This folder contains html files with bits of text. You need to modify the text.
- There is a line that says `Visit 2016's page` that needs to be changed. 
- The line below that one has something called [`href`](https://www.w3schools.com/tags/att_a_href.asp). That is a link to somewhere else. Right now, it links to the 2016 pages. Paste the link to the previous STuts/Tacos there in quotes -> these: " "

3. There is another link to the previous page in `/_includes/2023_data/intro.html`. You can choose to either remove that or also put the correct link there.

**Comment by nemas101** [comment]
The relevant file is the `/_includes/2023_data/speakers.html` - for future reference
