### ISSUE TITLE
Add paper resources for Tang's talk

### ISSUE THREAD

**Issue by BraveMoneyLute** [tacosConference/tacosConference.github.io#173]
No slides from him, but the papers the talk was based on:

Paper one: http://dx.doi.org/10.1121/10.0017247
2) http://dx.doi.org/10.3390/languages8020098
3) https://pubs.aip.org/asa/poma/article/50/1/060002/2879418/Lenition-measures-Neural-networks-posterior
4) https://doi.org/10.31234/osf.io/4wtc8
5) https://doi.org/10.17605/OSF.IO/GCH7S
There is also a poster but its not online: https://selma.ece.ufl.edu/2023/04/uf-undergraduate-research-symposium_poster-presentation/

**Comment by ansost** [comment]
Added with [857cf54](https://github.com/tacosConference/tacosConference.github.io/pull/174/commits/857cf545293cbe01fec7c30e08e5554dcac01126)
