### ISSUE TITLE
Replace social links/icons 

### ISSUE THREAD

**Issue by ansost** [tacosConference/tacosConference.github.io#2]
There is a Facebook and a Twitter icon with a link in the footer of the website. These currently don't link to out socials.

**Comment by BraveMoneyLute** [comment]
We can do this on Tuesday if anyone wants to try this out!

The file you need to change is the `_config.yaml` file.
Things that should also be changed are:
1. Title of our page (So it says `32. TaCoS`), add a description if needed
2. Change our url to `tacosconference.github.io/`
3. Comment out the Facebook social links for now
4. Add our `https://twitter.com/tacosconference` to the twitter social
