### ISSUE TITLE
Event Booklet link missing/broken

### ISSUE THREAD

**Issue by nemas101** [tacosConference/tacosConference.github.io#42]
I wanted to look at the event booklet we have linked but there isn't anything there anymore.
https://tacosconference.github.io/booklet
This could be bad if sponsors want to look at it. 
I don't know where to find and how to change the link.

**Comment by BraveMoneyLute** [comment]
Please scroll down to  "scholarships" and click the link that says "here", that is the place we linked with the brochure. The section you were looking for is still under construction and hasnt been edited yet.

**Comment by nemas101** [comment]
Okay, thanks. Should we maybe link the sponsor-booklet more prominently in that event-booklet-section until we have something there?

**Comment by ansost** [comment]
event boolket kann mit sponsor boolket ersetzt werden
