### ISSUE TITLE
Make Accomodation tab (like with speakers) 

### ISSUE THREAD

**Issue by alexanderclemen** [tacosConference/tacosConference.github.io#44]
Hier ist die Adresse:

DJH Jugendherberge Düsseldorf
Düsseldorfer Str. 1, 
40545 Düsseldorf

Busverbindung zur Uni dauern 20 Minuten
https://www.google.com/maps/dir/University+Dusseldorf:+Humanities,+Universit%C3%A4tsstra%C3%9Fe+1,+40225+D%C3%BCsseldorf,+Germany/DJH+Jugendherberge+D%C3%BCsseldorf,+D%C3%BCsseldorfer+Str.+1,+40545+D%C3%BCsseldorf/@51.2073217,6.7410264,13z/data=!3m2!4b1!5s0x47b8ca05e12f93d7:0x3dd099896c7809d7!4m18!4m17!1m5!1m1!1s0x47b8cb002ac3e3c3:0xe100c7ca17c2a04e!2m2!1d6.7946577!2d51.1893431!1m5!1m1!1s0x47b8ca05e1ed2abb:0x3d17d218c2ba6960!2m2!1d6.7577514!2d51.2268091!2m3!6e0!7e2!8j1674637200!3e3

**Comment by BraveMoneyLute** [comment]
done with next merge
