### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by ansost** [tacosConference/tacosConference.github.io#47]
The green and orange is not so pretty:D

I suggest we change it, preferably to something that is colorblind friendly as well. 

Something like this: 
https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

**Comment by BraveMoneyLute** [comment]
I am using 
#613B0B, #63A644, #DFAC2C, #9F130B, #D0811C
Which are the colours of our tacos logo
