### ISSUE TITLE
Have a IMPORTANT DATES section

### ISSUE THREAD

**Issue by BraveMoneyLute** [tacosConference/tacosConference.github.io#77]
please add your suggestions for dates in the comments

**Comment by ansost** [comment]
### Personally, I would just copy the Icphs website: https://www.icphs2023.org/
![image](https://user-images.githubusercontent.com/89185768/218247330-5321dac6-381d-4cce-a66d-df337506a528.png)

Our colors but same layout? Its nice and simple imo.
