### ISSUE TITLE
Image loads shittily

### ISSUE THREAD

**Issue by alexanderclemen** [tacosConference/tacosConference.github.io#79]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/119072458/217498568-8e497e4a-89d8-4e36-951e-bf0c922b5707.png">

**Comment by ansost** [comment]
nah, das war auf Alex PC. Das BIld wird so weit geladen, wie Bildschirm zusehen ist. Bei ihm geht seine Lesezeichenleiste weiter in den Bildschirm rein und daher ist weniger vom Bildschirm zu sehen, aka das Bild lädt auch nur bis dahin. Ganz komisch.

**Comment by ansost** [comment]
Der Rest der Seite ist normal geladen

**Comment by BraveMoneyLute** [comment]
Look into the CCS file at `/_includes/2023_css/agency.css` and scroll down to `line 338`

![Screenshot_20230210-114432_GitHub.jpg](https://user-images.githubusercontent.com/104856882/218073274-143e6d8e-e81e-411b-9e8a-c5be07269e05.jpg)

The header is set to 100vh which is 100% viewport height, so its relevant to how big each individual user's browser screen is. If you want to change that (I wouldnt), then an alternative is changing that to just `100%` for the full height of the image itself or you can choose some px number so its always fixed for every user.

**Comment by ansost** [comment]
Makes sense. Still good to know:) ill close this for now.
